ConsultingHub/force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Onboarding__c/fields/Availability_Date__c.field-meta.xml
<CustomField>
    <fullName>Availability_Date__c</fullName>
    <description>Date resource is available for staffing.</description>
    <inlineHelpText>Date resource is available for staffing.</inlineHelpText>
    <label>Availability Date</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/fields/Cloud__c.field-meta.xml
<CustomField>
    <fullName>Cloud__c</fullName>
    <label>Cloud</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/fields/Expected_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Completion_Date__c</fullName>
    <label>Expected Completion Date</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/fields/Trail_Guide__c.field-meta.xml
<CustomField>
    <fullName>Trail_Guide__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trail Guide</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Onboarding</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/classes/TestDataFactory.cls
//Contains methods to create sample data for test classes
@isTest
public class TestDataFactory {

    @isTest
    public static Onboarding__c createOnboardingRecord() {
        Onboarding__c ob = new Onboarding__c();
        ob.Name = 'test';
        ob.Trail_Guide__c = UserInfo.getUserId();
        ob.Cloud__c = 'Sales';
        ob.Start_Date__c = System.today();
        ob.Expected_Completion_Date__c = System.today() + 30;
        ob.Availability_Date__c = System.today() + 30;
        insert ob;
        
        return ob;
        
    }
}