ConsultingHub/force-app/main/default/objects/Business_Priorities__c/Business_Priorities__c.object-meta.xml
<CustomObject>
    <label>Business Priority</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Business Priority</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <label>Business Impact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Driver__c</fullName>
    <label>Business Value Driver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Lever__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Lever__c</fullName>
    <label>Business Value Lever</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/Business_Priority_Product_Features__c.object-meta.xml
<CustomObject>
    <label>Business Priority - Product Features</label>
    <nameField>
        <displayFormat>BPF-{000000}</displayFormat>
        <label>Business Priority - Product Features Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priority - Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Business_Priority__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority__c</fullName>
    <label>Business Priority</label>
    <referenceTo>Business_Priorities__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature__c</fullName>
    <label>Product Feature</label>
    <referenceTo>Product_Feature__c</referenceTo>
    <relationshipLabel>Business Priorities</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Business_Unit__c</fullName>
    <formula>TEXT(Product_Feature__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Business Unit</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Name__c</fullName>
    <formula>Product_Feature__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Name</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Product_Area__c</fullName>
    <formula>TEXT(Product_Feature__r.Product_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Product Area</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Product_Subarea__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Product_Subarea__c</fullName>
    <formula>TEXT(Product_Feature__r.Product_Sub_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Product Subarea</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/Engagement_Product_Feature__c.object-meta.xml
<CustomObject>
    <label>Engagement Product Feature</label>
    <nameField>
        <displayFormat>EPF-{00000000}</displayFormat>
        <label>Engagement Product Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Product_Feature__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Product Features</relationshipLabel>
    <relationshipName>Engagement_Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Engagement_Product_Feature_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Product_Feature_External_Id__c</fullName>
    <description>Format of external id is Product_Feature__c+Engagement__c</description>
    <externalId>true</externalId>
    <inlineHelpText>Format of external id is Product_Feature__c+Engagement__c</inlineHelpText>
    <label>Engagement Product Feature External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Area__c</fullName>
    <formula>TEXT( Product_Feature__r.Product_Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Area</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Product_Feature__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature__c</fullName>
    <label>Product Feature</label>
    <referenceTo>Product_Feature__c</referenceTo>
    <relationshipLabel>Engagement Product Features</relationshipLabel>
    <relationshipName>Engagement_Product_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Product_Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Area__c</fullName>
    <formula>TEXT( Product_Feature__r.Product_Sub_Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sub Area</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/ia_Engagement_Value__c.object-meta.xml
<CustomObject>
    <description>Created for users to be able to create value story details</description>
    <label>Engagement Value</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Engagement Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <formula>Value_Driver__r.Business_Impact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Impact</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Priority__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority__c</fullName>
    <label>Business Priority</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Driver__c</fullName>
    <formula>Value_Driver__r.Business_Value_Driver__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Value Driver</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Value_Lever__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Lever__c</fullName>
    <formula>Value_Driver__r.Business_Value_Lever__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Value Lever</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Values</relationshipLabel>
    <relationshipName>Engagement_Value</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Engagement_Value_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Value_External_Id__c</fullName>
    <description>External id format is Value_Driver__c + Engagement__c</description>
    <externalId>true</externalId>
    <inlineHelpText>External id format is Value_Driver__c + Engagement__c</inlineHelpText>
    <label>Engagement Value External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Value_Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Value Driver</label>
    <referenceTo>Business_Priorities__c</referenceTo>
    <relationshipLabel>Engagement Values</relationshipLabel>
    <relationshipName>Engagement_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/Product_Feature__c.object-meta.xml
<CustomObject>
    <description>Products from Org62 
https://org62.lightning.force.com/lightning/r/Report/00O0M000008kd8NUAQ/view?queryScope=userFolders</description>
    <label>Product Feature</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analytics Cloud</fullName>
            </value>
            <value>
                <fullName>Community Cloud</fullName>
            </value>
            <value>
                <fullName>Einstein</fullName>
            </value>
            <value>
                <fullName>Field Service Lightning</fullName>
            </value>
            <value>
                <fullName>Lightning Platform</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Area__c</fullName>
    <label>Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Einstein Analytics</fullName>
            </value>
            <value>
                <fullName>Einstein Discovery</fullName>
            </value>
            <value>
                <fullName>Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>Service Delivery</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>DXP (Digital Experience Platform)</fullName>
            </value>
            <value>
                <fullName>Partner Experience Management</fullName>
            </value>
            <value>
                <fullName>Self Service Communities</fullName>
            </value>
            <value>
                <fullName>Einstein Platform</fullName>
            </value>
            <value>
                <fullName>Einstein Prediction Builder</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Dispatch Management</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
            <value>
                <fullName>Mobile Experience &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Products, Assets, &amp; Inventory</fullName>
            </value>
            <value>
                <fullName>Resource &amp; Time Management</fullName>
            </value>
            <value>
                <fullName>Scheduling &amp; Optimization</fullName>
            </value>
            <value>
                <fullName>Service Contracts &amp; Entitlements</fullName>
            </value>
            <value>
                <fullName>Work Management</fullName>
            </value>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Analytics Builder</fullName>
            </value>
            <value>
                <fullName>Audience Builder</fullName>
            </value>
            <value>
                <fullName>Audience Studio</fullName>
            </value>
            <value>
                <fullName>Automation Studio</fullName>
            </value>
            <value>
                <fullName>Content Builder</fullName>
            </value>
            <value>
                <fullName>Distributed Marketing</fullName>
            </value>
            <value>
                <fullName>Email Studio</fullName>
            </value>
            <value>
                <fullName>Google Analytics</fullName>
            </value>
            <value>
                <fullName>Interaction Studio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/classes/FeatureValueStoryController.cls
public class FeatureValueStoryController {

    
    @AuraEnabled
    public static List<String> fetchBusinessValueLevers() {
    	Set<String> businessValueLevers = new Set<String>();
        for(Business_Priorities__c bp :[	select	id, Business_Value_Lever__c
                							from 		Business_Priorities__c ]) 
        {
        	businessValueLevers.add(bp.Business_Value_Lever__c);    
        }
        List<String> businessValueLeversList = new List<String>();
        businessValueLeversList.addAll(businessValueLevers);
        businessValueLeversList.sort();
        return businessValueLeversList;
    }
    
    
    @AuraEnabled
    public static List<String> fetchBusinessImpacts(String selectBusValueLever) {
    	Set<String> businessImpacts = new Set<String>();
        for(Business_Priorities__c bp :[	select	id, Business_Impact__c
                                        	from	Business_Priorities__c 
                                       		where 	Business_Value_Lever__c =:selectBusValueLever]) 
        {
        	businessImpacts.add(bp.Business_Impact__c);    
        }
        List<String> businessImpactsList = new List<String>();
        businessImpactsList.addAll(businessImpacts);
        businessImpactsList.sort();
        return businessImpactsList;
    }
    
    @AuraEnabled
    public static List<Business_Priorities__c> fetchBusinessPriorities( String selectBusValueLever, String selectBusImpact ) {
    	
        return [ 	select		id, Name, Business_Impact__c,Business_Value_Lever__c, Business_Value_Driver__c
                	from 		Business_Priorities__c 
                	where 		Business_Value_Lever__c = :selectBusValueLever
                		and		Business_Impact__c = :selectBusImpact
               		order by	Business_Value_Driver__c];
    }
    
    
    @AuraEnabled
    public static List <Business_Priority_Product_Features__c> matchBusinessPrioritywithProductFeature( List<String> bpIds ) {
        
        return [select	Id, Name, Product_Feature_Name__c, Product_Feature_Business_Unit__c,
               			Product_Feature_Product_Area__c, Product_Feature_Product_Subarea__c 
               from		Business_Priority_Product_Features__c
               where	Business_Priority__c IN :bpIds
               order by Product_Feature_Name__c];
    }
    
    @AuraEnabled
    public static void addBusinessPrioritiesAndProdFeatures( List<String> bpIds, List<String> pfIds, String currentEngagementId, Boolean productMode) {
       List<ia_Engagement_Value__c> engValues = new List<ia_Engagement_Value__c>();
        for(String bpId :bpIds) {
            engValues.add(
                new ia_Engagement_Value__c(
                    Value_Driver__c = bpId, 
                    Engagement__c = currentEngagementId,
                    Engagement_Value_External_Id__c	= bpId + currentEngagementId
                )
            );
        } 
        upsert engValues Engagement_Value_External_Id__c;
        
        List<Engagement_Product_Feature__c> engProdFeatures = new List<Engagement_Product_Feature__c>();
        if(productMode == false) {
            for(Business_Priority_Product_Features__c bppf : [select	Id, Product_Feature__c 
                                                               from		Business_Priority_Product_Features__c
                                                               where	Id IN :pfIds])
            {
                engProdFeatures.add(
                    new Engagement_Product_Feature__c(
                        Product_Feature__c=bppf.Product_Feature__c, 
                        Engagement__c =currentEngagementId,
                        Engagement_Product_Feature_External_Id__c= bppf.Product_Feature__c + currentEngagementId
                    )
                );
            }
        }
        else {
            for(String pfId : pfIds)
            {
                engProdFeatures.add(
                    new Engagement_Product_Feature__c(
                        Product_Feature__c=pfId, 
                        Engagement__c =currentEngagementId,
                        Engagement_Product_Feature_External_Id__c= pfId + currentEngagementId
                    )
                );
            }
        }
        
        upsert engProdFeatures Engagement_Product_Feature_External_Id__c;
    }
    
    /////////////////////////////////////////////////////////////////////////
    //
    //
    
    @AuraEnabled
    public static List<String> fetchProdBusUnit() {
    	Set<String> prodBusUnit = new Set<String>();
        for(Product_Feature__c  pf :[	select	id, Business_Unit__c 
                                     from 	Product_Feature__c  ]) 
        {
        	prodBusUnit.add(pf.Business_Unit__c);    
        }
        List<String> prodBusUnitList = new List<String>();
        prodBusUnitList.addAll(prodBusUnit);
        prodBusUnitList.sort();
        return prodBusUnitList;
    }
    
    @AuraEnabled
    public static List<String> fetchProductArea( String selectedBusUnit) {
    	Set<String> prodBusUnit = new Set<String>();
        for(Product_Feature__c  pf :[	select	id, Product_Area__c  
                                     	from 	Product_Feature__c 
                                    	where 	Business_Unit__c = :selectedBusUnit]) 
        {
        	prodBusUnit.add(pf.Product_Area__c );    
        }
        List<String> prodBusUnitList = new List<String>();
        prodBusUnitList.addAll(prodBusUnit);
        prodBusUnitList.sort();
        return prodBusUnitList;
    }
    @AuraEnabled
    public static List<Product_Feature__c> fetchProductFeatures( String selectedProdBusUnit, String selectedProdArea) {
        return [select	id, Name, Product_Sub_Area__c   
                from 	Product_Feature__c 
                where 	Business_Unit__c = :selectedProdBusUnit
                	and Product_Area__c = :selectedProdArea];
        
    }
    
    
    @AuraEnabled
    public static List <Business_Priorities__c> matchProductFeatureWithBusinessPriority( List<String> pfIds ) {
        Set<String> bpIds = new Set<String>();
        for( Business_Priority_Product_Features__c bppf:
            [	select	Id, Business_Priority__c
               	from	Business_Priority_Product_Features__c
               	where	Product_Feature__c IN :pfIds])
        {
            bpIds.add(bppf.Business_Priority__c);
        }
        
        return [ 	select		id, Name, Business_Impact__c,Business_Value_Lever__c, Business_Value_Driver__c
                	from 		Business_Priorities__c 
                	where 		Id IN:bpIds
               		order by	Business_Value_Lever__c,Business_Impact__c, Business_Value_Driver__c];
    }
    
    //VH changes 
    @AuraEnabled
    public static List<Business_Priority_Product_Features__c> fetchSuggestedAssociations(List<String> bpIds) {
        String str_bpIds ='';
        for (String varStr:bpIds){
            str_bpIds = str_bpIds + varStr +',';
        }
        System.debug('------>concatenated string of bpIds is='+str_bpIds);
        
        List<Business_Priority_Product_Features__c> associationsList = [select	Id, Name, Product_Feature_Name__c, Product_Feature_Business_Unit__c,
                                                                        		Product_Feature_Product_Area__c, Product_Feature_Product_Subarea__c 
                                                                       	from	Business_Priority_Product_Features__c
                                                                       	where	Business_Priority__c in ( :str_bpIds )
                                                                       	order by Product_Feature_Name__c];
		return associationsList;
    }
    
}