ConsultingHub/force-app/main/default/objects/Business_Priorities__c/Business_Priorities__c.object-meta.xml
<CustomObject>
    <label>Business Priority</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Business Priority</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <label>Business Impact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Driver__c</fullName>
    <label>Business Value Driver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Lever__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Lever__c</fullName>
    <label>Business Value Lever</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Strategic_Focus__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Focus__c</fullName>
    <label>Strategic Focus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/VCM_Clouds__c.field-meta.xml
<CustomField>
    <fullName>VCM_Clouds__c</fullName>
    <label>VCM Clouds</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/Business_Priority_Product_Features__c.object-meta.xml
<CustomObject>
    <label>Business Priority - Product Features</label>
    <nameField>
        <displayFormat>BPF-{000000}</displayFormat>
        <label>Business Priority - Product Features Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priority - Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Business_Priority__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority__c</fullName>
    <label>Business Priority</label>
    <referenceTo>Business_Priorities__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Business Priority Id + Product Feature Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature__c</fullName>
    <label>Product Feature</label>
    <referenceTo>Product_Feature__c</referenceTo>
    <relationshipLabel>Business Priorities</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/Engagement_Product_Feature__c.object-meta.xml
<CustomObject>
    <label>Engagement Product Feature</label>
    <nameField>
        <displayFormat>EPF-{00000000}</displayFormat>
        <label>Engagement Product Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Product_Feature__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Product Features</relationshipLabel>
    <relationshipName>Engagement_Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Area__c</fullName>
    <formula>TEXT( Product_Feature__r.Product_Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Area</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Product_Feature__c/fields/Product_Feature__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature__c</fullName>
    <label>Product Feature</label>
    <referenceTo>Product_Feature__c</referenceTo>
    <relationshipLabel>Engagement Product Features</relationshipLabel>
    <relationshipName>Engagement_Product_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/ia_Engagement__c.object-meta.xml
<CustomObject>
    <description>Document details of on going and completed engagements</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Implementation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Implementation_Type</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Managed By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Project_Management</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/ia_Engagement_Value__c.object-meta.xml
<CustomObject>
    <description>Created for users to be able to create value story details</description>
    <label>Engagement Value</label>
    <nameField>
        <displayFormat>EV-{00000}</displayFormat>
        <label>Engagement Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <formula>Value_Driver__r.Business_Impact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Impact</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Priority__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority__c</fullName>
    <label>Business Priority</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Driver__c</fullName>
    <formula>Value_Driver__r.Business_Value_Driver__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Value Driver</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Business_Value_Lever__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Lever__c</fullName>
    <formula>Value_Driver__r.Business_Value_Lever__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Value Lever</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Value__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Values</relationshipLabel>
    <relationshipName>Engagement_Value</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/Product_Feature__c.object-meta.xml
<CustomObject>
    <description>Products from Org62 
https://org62.lightning.force.com/lightning/r/Report/00O0M000008kd8NUAQ/view?queryScope=userFolders</description>
    <label>Product Feature</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analytics Cloud</fullName>
            </value>
            <value>
                <fullName>Community Cloud</fullName>
            </value>
            <value>
                <fullName>Einstein</fullName>
            </value>
            <value>
                <fullName>Field Service Lightning</fullName>
            </value>
            <value>
                <fullName>Lightning Platform</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Area__c</fullName>
    <label>Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Einstein Analytics</fullName>
            </value>
            <value>
                <fullName>Einstein Discovery</fullName>
            </value>
            <value>
                <fullName>Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>Service Delivery</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>DXP (Digital Experience Platform)</fullName>
            </value>
            <value>
                <fullName>Partner Experience Management</fullName>
            </value>
            <value>
                <fullName>Self Service Communities</fullName>
            </value>
            <value>
                <fullName>Einstein Platform</fullName>
            </value>
            <value>
                <fullName>Einstein Prediction Builder</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Dispatch Management</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
            <value>
                <fullName>Mobile Experience &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Products, Assets, &amp; Inventory</fullName>
            </value>
            <value>
                <fullName>Resource &amp; Time Management</fullName>
            </value>
            <value>
                <fullName>Scheduling &amp; Optimization</fullName>
            </value>
            <value>
                <fullName>Service Contracts &amp; Entitlements</fullName>
            </value>
            <value>
                <fullName>Work Management</fullName>
            </value>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Analytics Builder</fullName>
            </value>
            <value>
                <fullName>Audience Builder</fullName>
            </value>
            <value>
                <fullName>Audience Studio</fullName>
            </value>
            <value>
                <fullName>Automation Studio</fullName>
            </value>
            <value>
                <fullName>Content Builder</fullName>
            </value>
            <value>
                <fullName>Distributed Marketing</fullName>
            </value>
            <value>
                <fullName>Email Studio</fullName>
            </value>
            <value>
                <fullName>Google Analytics</fullName>
            </value>
            <value>
                <fullName>Interaction Studio</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/classes/MatchProductFeaturesControllerTest.cls
@isTest
public class MatchProductFeaturesControllerTest {
    
        
	@isTest static void fetchBusinessPriorities_Test(){
        Test.startTest();
        Business_Priorities__c bp = new Business_Priorities__c();
        bp.Business_Impact__c = 'Agility & Flexibility1';
        bp.Business_Value_Driver__c ='TEST';
        bp.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        bp.VCM_Clouds__c  = 'Platform';
        
        Business_Priorities__c bp2 = new Business_Priorities__c();
        bp2.Business_Impact__c = 'Agility & Flexibility1';
        bp2.Business_Value_Driver__c ='TEST2';
        bp2.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        bp2.VCM_Clouds__c  = 'Platform';
        
        insert bp;
        insert bp2;
        
        Test.stopTest();
        
        List<String> m_bus_priorities = MatchProductFeaturesController.fetchBusinessPriorities();
        System.debug('..1-->MatchProductFeaturesControllerTest-->fetchBusinessPriorities_Test m_bus_priorities.size()='+m_bus_priorities.size());
        System.assertEquals(1, m_bus_priorities.size(), 'fetchBusinessPriorities_Test -> size is one');
        
    }
    
    	@isTest static void fetchBusinessPrioritiesForSelectedCloud_Test(){
        Test.startTest();
        Business_Priorities__c bp = new Business_Priorities__c();
        bp.Business_Impact__c = 'Agility & Flexibility1';
        bp.Business_Value_Driver__c ='TEST';
        bp.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        bp.VCM_Clouds__c  = 'Platform';
        bp.Strategic_Focus__c = 'Improve Operating Model';
        
        Business_Priorities__c bp2 = new Business_Priorities__c();
        bp2.Business_Impact__c = 'Agility & Flexibility1';
        bp2.Business_Value_Driver__c ='TEST2';
        bp2.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        bp2.VCM_Clouds__c  = 'Platform';
        bp2.Strategic_Focus__c = 'Improve Operating Model';
            
        insert bp;
        insert bp2;
        
        Test.stopTest();
        
        List<Business_Priorities__c> m_bus_priorities = MatchProductFeaturesController.fetchBusinessPrioritiesForSelectedCloud('Platform');
        System.debug('..1-->MatchProductFeaturesControllerTest-->fetchBusinessPrioritiesForSelectedCloud_Test m_bus_priorities.size()='+m_bus_priorities.size());
        System.assertEquals(2, m_bus_priorities.size(), 'fetchBusinessPrioritiesForSelectedCloud_Test -> size is two');
        
    }
    
    @isTest static void matchBusinessPrioritywithProductFeature_Test(){
                
        Test.startTest();
        List<String> pf_List = new List<String>();

        //add product feature
        Product_Feature__c pf = new Product_Feature__c();
        pf.Business_Unit__c = 'Service Cloud';
        pf.Product_Area__c ='Knowledge';
        
        Product_Feature__c pf2 = new Product_Feature__c();
        pf2.Business_Unit__c = 'Service Cloud';
        pf2.Product_Area__c ='Knowledge';
        
        insert pf;
        insert pf2;
        
        pf_List.add(pf.Id);
        pf_List.add(pf2.Id);
        
        Test.stopTest();
        Boolean showAll = true;
        
        List<Product_Feature__c> pf_queryList = MatchProductFeaturesController.matchBusinessPrioritywithProductFeature('Service Cloud',showAll);
        System.debug('---> 1 --> matchBusinessPrioritywithProductFeature_Test ------------> size()='+ pf_queryList.size());
        System.assertEquals(2,pf_queryList.size(), 'matchBusinessPrioritywithProductFeature_Test -> size is 2');
        
        showAll = false;
        List<Product_Feature__c> pf_queryList2 = MatchProductFeaturesController.matchBusinessPrioritywithProductFeature('Service Cloud',showAll);
        System.debug('---> 1 --> matchBusinessPrioritywithProductFeature_Test ------------> size()='+ pf_queryList2.size());
        System.assertEquals(2,pf_queryList2.size(), 'matchBusinessPrioritywithProductFeature_Test -> size is 2');
    }
    
        @isTest static void addBP_And_PF_Test(){
		
        Test.startTest();
        List<String> bpIds = new List<String>();
        List<String> pfIds = new List<String>();
        
        //add business priority
        Business_Priorities__c bp = new Business_Priorities__c();
        bp.Business_Impact__c = 'Agility & Flexibility1';
        bp.Business_Value_Driver__c ='TEST';
        bp.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        
        Business_Priorities__c bp2 = new Business_Priorities__c();
        bp2.Business_Impact__c = 'Agility & Flexibility1';
        bp2.Business_Value_Driver__c ='TEST';
        bp2.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        
        insert bp;
        insert bp2;
        
        //add product feature
        Product_Feature__c pf = new Product_Feature__c();
        pf.Business_Unit__c = 'Service Cloud';
        pf.Product_Area__c ='Knowledge';
        
        Product_Feature__c pf2 = new Product_Feature__c();
        pf2.Business_Unit__c = 'Service Cloud';
        pf2.Product_Area__c ='Knowledge';
        
        insert pf;
        insert pf2;
        
        bpIds.add(bp.Id);
        bpIds.add(bp2.Id);
        
        pfIds.add(pf.Id);
        pfIds.add(pf2.Id);
        
        ia_Engagement__c m_engage = new ia_Engagement__c();
        m_engage.Name = 'Testing 123';
        m_engage.Implementation_Type__c = 'New';
		m_engage.Project_Type__c = 'Customer';
        
        insert m_engage;
        
        //add Business_Priority_Product_Features__c
        Business_Priority_Product_Features__c bpf = new Business_Priority_Product_Features__c();
        bpf.Business_Priority__c = bp.Id ;
        bpf.Product_Feature__c = pf.Id;
        bpf.External_Id__c ='a491U0000001mg0QAAa631U0000004ZWFQA2';
        
        insert bpf;
                
        MatchProductFeaturesController.associateBusinessPrioritywithProductFeature(bpIds,pfIds);
        List<Business_Priority_Product_Features__c> bp_pf = [select Id, Name,Business_Priority__c,
                        									Product_Feature__c,
                        									External_Id__c 
                                                            from Business_Priority_Product_Features__c ];

		/*
		List<ia_Engagement_Value__c> engValues = [select Id, Name from ia_Engagement_Value__c ];
		
        productMode = false;
        
        Engagement_Product_Feature__c m_eng_prod_feat = new Engagement_Product_Feature__c();
        m_eng_prod_feat.Product_Feature__c = pf.Id;
        m_eng_prod_feat.Engagement__c = 'a481F0000001kuMQAQ';
        insert m_eng_prod_feat;
            
        FeatureValueStoryController.MatchProductFeaturesController(bpIds,pfIds,m_engage.Id,productMode);
        List<Engagement_Product_Feature__c> epf_Values = [select Id, Name from Engagement_Product_Feature__c ];
        */
            
        Test.stopTest();
        
        System.debug('---> addBP_And_PF_Test bp_pf.size()='+bp_pf.size() );
        
        System.assertEquals(5,bp_pf.size(), '11111 bp_pf.size()-> size is 5');
        
    }

    
	@isTest static void fetchExistingAssociations_Test(){
		
        Test.startTest();
        List<String> bpIds = new List<String>();
        List<String> pfIds = new List<String>();
        
        //add business priority
        Business_Priorities__c bp = new Business_Priorities__c();
        bp.Business_Impact__c = 'Agility & Flexibility1';
        bp.Business_Value_Driver__c ='TEST';
        bp.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        
        Business_Priorities__c bp2 = new Business_Priorities__c();
        bp2.Business_Impact__c = 'Agility & Flexibility1';
        bp2.Business_Value_Driver__c ='TEST';
        bp2.Business_Value_Lever__c ='Enhance Strategic Capabilities1';
        
        insert bp;
        insert bp2;
        
        //add product feature
        Product_Feature__c pf = new Product_Feature__c();
        pf.Business_Unit__c = 'Service Cloud';
        pf.Product_Area__c ='Knowledge';
        
        Product_Feature__c pf2 = new Product_Feature__c();
        pf2.Business_Unit__c = 'Service Cloud';
        pf2.Product_Area__c ='Knowledge';
        
        insert pf;
        insert pf2;
        
        bpIds.add(bp.Id);
        bpIds.add(bp2.Id);
        
        pfIds.add(pf.Id);
        pfIds.add(pf2.Id);
        
        ia_Engagement__c m_engage = new ia_Engagement__c();
        m_engage.Name = 'Testing 123';
        m_engage.Implementation_Type__c = 'New';
		m_engage.Project_Type__c = 'Customer';
        
        insert m_engage;
        
        //add Business_Priority_Product_Features__c
        Business_Priority_Product_Features__c bpf = new Business_Priority_Product_Features__c();
        bpf.Business_Priority__c = bp.Id ;
        bpf.Product_Feature__c = pf.Id;
        bpf.External_Id__c ='a491U0000001mg0QAAa631U0000004ZWFQA2';
        
        insert bpf;
                
        List<Business_Priority_Product_Features__c> m_list = MatchProductFeaturesController.fetchExistingAssociations(bp.Id);
           
        Test.stopTest();
        
        System.debug('---> fetchExistingAssociations_Test m_list.size()='+m_list.size() );
        
        System.assertEquals(1,m_list.size(), '11111 fetchExistingAssociations_Test m_list.size()-> size is 2');
        
    }
}