ConsultingHub/force-app/main/default/objects/Business_Priorities__c/Business_Priorities__c.object-meta.xml
<CustomObject>
    <label>Business Priority</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Business Priority</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <label>Business Impact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Driver__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Driver__c</fullName>
    <label>Business Value Driver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Business_Value_Lever__c.field-meta.xml
<CustomField>
    <fullName>Business_Value_Lever__c</fullName>
    <label>Business Value Lever</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/Strategic_Focus__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Focus__c</fullName>
    <label>Strategic Focus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priorities__c/fields/VCM_Clouds__c.field-meta.xml
<CustomField>
    <fullName>VCM_Clouds__c</fullName>
    <label>VCM Clouds</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/Business_Priority_Product_Features__c.object-meta.xml
<CustomObject>
    <label>Business Priority - Product Features</label>
    <nameField>
        <displayFormat>BPF-{000000}</displayFormat>
        <label>Business Priority - Product Features Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Priority - Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Business_Priority__c.field-meta.xml
<CustomField>
    <fullName>Business_Priority__c</fullName>
    <label>Business Priority</label>
    <referenceTo>Business_Priorities__c</referenceTo>
    <relationshipLabel>Product Features</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Business Priority Id + Product Feature Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature__c</fullName>
    <label>Product Feature</label>
    <referenceTo>Product_Feature__c</referenceTo>
    <relationshipLabel>Business Priorities</relationshipLabel>
    <relationshipName>Business_Priority_Product_Features</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Business_Unit__c</fullName>
    <formula>TEXT(Product_Feature__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Business Unit</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Name__c</fullName>
    <formula>Product_Feature__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Name</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Product_Area__c</fullName>
    <formula>TEXT(Product_Feature__r.Product_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Product Area</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Business_Priority_Product_Features__c/fields/Product_Feature_Product_Subarea__c.field-meta.xml
<CustomField>
    <fullName>Product_Feature_Product_Subarea__c</fullName>
    <formula>TEXT(Product_Feature__r.Product_Sub_Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Feature Product Subarea</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/Product_Feature__c.object-meta.xml
<CustomObject>
    <description>Products from Org62 
https://org62.lightning.force.com/lightning/r/Report/00O0M000008kd8NUAQ/view?queryScope=userFolders</description>
    <label>Product Feature</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Feature Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analytics Cloud</fullName>
            </value>
            <value>
                <fullName>Community Cloud</fullName>
            </value>
            <value>
                <fullName>Einstein</fullName>
            </value>
            <value>
                <fullName>Field Service Lightning</fullName>
            </value>
            <value>
                <fullName>Lightning Platform</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Product_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Area__c</fullName>
    <label>Product Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Einstein Analytics</fullName>
            </value>
            <value>
                <fullName>Einstein Discovery</fullName>
            </value>
            <value>
                <fullName>Reports &amp; Dashboards</fullName>
            </value>
            <value>
                <fullName>Service Delivery</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>DXP (Digital Experience Platform)</fullName>
            </value>
            <value>
                <fullName>Partner Experience Management</fullName>
            </value>
            <value>
                <fullName>Self Service Communities</fullName>
            </value>
            <value>
                <fullName>Einstein Platform</fullName>
            </value>
            <value>
                <fullName>Einstein Prediction Builder</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Dispatch Management</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
            <value>
                <fullName>Mobile Experience &amp; Apps</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Products, Assets, &amp; Inventory</fullName>
            </value>
            <value>
                <fullName>Resource &amp; Time Management</fullName>
            </value>
            <value>
                <fullName>Scheduling &amp; Optimization</fullName>
            </value>
            <value>
                <fullName>Service Contracts &amp; Entitlements</fullName>
            </value>
            <value>
                <fullName>Work Management</fullName>
            </value>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Analytics Builder</fullName>
            </value>
            <value>
                <fullName>Audience Builder</fullName>
            </value>
            <value>
                <fullName>Audience Studio</fullName>
            </value>
            <value>
                <fullName>Automation Studio</fullName>
            </value>
            <value>
                <fullName>Content Builder</fullName>
            </value>
            <value>
                <fullName>Distributed Marketing</fullName>
            </value>
            <value>
                <fullName>Email Studio</fullName>
            </value>
            <value>
                <fullName>Google Analytics</fullName>
            </value>
            <value>
                <fullName>Interaction Studio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Product_Feature__c/fields/Product_Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Area__c</fullName>
    <label>Product Sub Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>App Framework</fullName>
            </value>
            <value>
                <fullName>Capacity optimization</fullName>
            </value>
            <value>
                <fullName>Charting</fullName>
            </value>
            <value>
                <fullName>Communities</fullName>
            </value>
            <value>
                <fullName>Connectors</fullName>
            </value>
            <value>
                <fullName>Dashboard Builder</fullName>
            </value>
            <value>
                <fullName>Data Prep ( Dataflow, Data Recipes, Replication)</fullName>
            </value>
            <value>
                <fullName>Einstein Discovery</fullName>
            </value>
            <value>
                <fullName>Einstein Prediction Builder</fullName>
            </value>
            <value>
                <fullName>Embedded Analytics</fullName>
            </value>
            <value>
                <fullName>Encryption and Data Security</fullName>
            </value>
            <value>
                <fullName>End User experience</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Enterprise Business Platform</fullName>
            </value>
            <value>
                <fullName>Explorer / Query Builder</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Industry Analytics Products</fullName>
            </value>
            <value>
                <fullName>ISVs</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Query Engine</fullName>
            </value>
            <value>
                <fullName>Sales Analytics App</fullName>
            </value>
            <value>
                <fullName>Scalability &amp; Performance</fullName>
            </value>
            <value>
                <fullName>SDK/Developers/Voice</fullName>
            </value>
            <value>
                <fullName>Service Analytics App</fullName>
            </value>
            <value>
                <fullName>Superpod architecture</fullName>
            </value>
            <value>
                <fullName>Tables</fullName>
            </value>
            <value>
                <fullName>Templates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/classes/MatchProductFeaturesController.cls
public class MatchProductFeaturesController {

    @AuraEnabled
    public static List<String> fetchBusinessPriorities() {
    	Set<String> businessPriorityVCMClouds = new Set<String>();
        for( Business_Priorities__c bp: [	select 		Id, Name, VCM_Clouds__c  
              								from 		Business_Priorities__c])
        {
            if(String.isNotBlank(bp.VCM_Clouds__c)) {
                businessPriorityVCMClouds.add(bp.VCM_Clouds__c.trim());
            }
        }
        List<String> businessPriorityVCMCloudsList = new List<String>();
        businessPriorityVCMCloudsList.addAll(businessPriorityVCMClouds);
        businessPriorityVCMCloudsList.sort();
        return businessPriorityVCMCloudsList;
    }
    
    
    @AuraEnabled
    public static List <String> fetchProductFeatures() {
    	return null;
    }
    
    @AuraEnabled
    public static List<Business_Priorities__c> fetchBusinessPrioritiesForSelectedCloud( String selectedVCMCloud ) {
    	
        return [ 	select		id, Name, Business_Impact__c,Business_Value_Lever__c, Business_Value_Driver__c, 
                				Strategic_Focus__c, VCM_Clouds__c
                	from 		Business_Priorities__c 
                	where 		VCM_Clouds__c = :selectedVCMCloud
               		order by	Business_Value_Lever__c, Business_Impact__c, Business_Value_Driver__c];
    }
    
    @AuraEnabled
    public static List <Product_Feature__c> matchBusinessPrioritywithProductFeature( String selectedVCMCloud, Boolean showAll ) {
        if(showAll) {
            return	[	SELECT		Id, Name, Business_Unit__c, Product_Area__c, Product_Sub_Area__c  
                     	FROM		Product_Feature__c 
                    	ORDER BY	Business_Unit__c, Product_Area__c, Product_Sub_Area__c];
        }
        else {
            String selectedVCMCloudReplaced = selectedVCMCloud.replace('/','');
    
            List<String> partialMatches = new List<String>();
            for (String fragment : selectedVCMCloudReplaced.split(' '))
            {
                if(fragment.trim().length() > 0){
                    partialMatches.add('%' + fragment + '%');
                }
                    
            }
            return	[	SELECT		Id, Name, Business_Unit__c, Product_Area__c, Product_Sub_Area__c  
                     	FROM		Product_Feature__c  
                     	WHERE		Product_Area__c 	LIKE :partialMatches
                        	OR		Business_Unit__c 	LIKE :partialMatches
                    	ORDER BY	Business_Unit__c, Product_Area__c, Product_Sub_Area__c];
        }
    }
    
    @AuraEnabled
    public static void associateBusinessPrioritywithProductFeature( List<String> selectedBusinessPrioritiesIds, List<String> selectedProductFeatureIds ) {
    	system.debug('selectedBusinessPrioritiesIds='+selectedBusinessPrioritiesIds);
        system.debug('selectedProductFeatureIds='+selectedProductFeatureIds);
        
        List<Business_Priority_Product_Features__c> junctionList = new List<Business_Priority_Product_Features__c>();
        
        for(String bpId :selectedBusinessPrioritiesIds) {
            for(String pfId :selectedProductFeatureIds) {
                junctionList.add( 
                    new Business_Priority_Product_Features__c(
                        Business_Priority__c = bpId,
                        Product_Feature__c = pfId,
                        External_Id__c = bpId + pfId 
                    )
                );
            }
        }
        
        system.debug('junctionList='+junctionList);
        if(junctionList.size() > 0) {
            upsert junctionList External_Id__c;
        }
    }
    
    @AuraEnabled
    public static List<Business_Priority_Product_Features__c> fetchExistingAssociations(String bpId) {
        
        List<Business_Priority_Product_Features__c> associationsList = [select	Id, Name, Product_Feature_Name__c, Product_Feature_Business_Unit__c,
                                                                        		Product_Feature_Product_Area__c, Product_Feature_Product_Subarea__c 
                                                                       	from	Business_Priority_Product_Features__c
                                                                       	where	Business_Priority__c = :bpId
                                                                       	order by Product_Feature_Name__c];
		return associationsList;
    }
    
}