ConsultingHub/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Junction object that connects Onboarding record &amp; Learning records</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Actual_Hours_Spent__c.field-meta.xml
<CustomField>
    <fullName>Actual_Hours_Spent__c</fullName>
    <label>Actual Hours Spent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Hours_Required__c.field-meta.xml
<CustomField>
    <fullName>Hours_Required__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Must_Complete_By__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete_By__c</fullName>
    <label>Must Complete By</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Previously Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Onboarding__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/classes/GetRelatedModules.cls
/**
 * @description       : Gets related Modules associated to a specific Onboarding Record
 * @author            : Charles Gallagher
 * @last modified on  : 05-26-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-26-2021   Charles Gallagher  Initial Version
**/
public class GetRelatedModules 
{
	@AuraEnabled(cacheable=true)
    public static List<Module__c> getModules(Id onboardingId)
    {
        List<Module__c> modulesToReturn = new List<Module__c>();
        try
        {
            modulesToReturn = [Select Id, Name, Status__c, Must_Complete_By__c, Hours_Required__c, Actual_Hours_Spent__c 
                               From Module__c 
                               Where Onboarding__c =: onboardingId 
                               ORDER BY Sort_Order__c ASC];
        }
        catch(Exception ex)
        {
            System.debug('Exception: ' + ex);
        }
        return modulesToReturn;
    }
}