ConsultingHub/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Expected_Hours_to_Complete__c.field-meta.xml
<CustomField>
    <fullName>Expected_Hours_to_Complete__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Learning_Domain__c.field-meta.xml
<CustomField>
    <fullName>Learning_Domain__c</fullName>
    <label>Learning Domain</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JIA</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Must_Complete__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Must Complete</label>
    <type>Checkbox</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product Learning</fullName>
            </value>
            <value>
                <fullName>Role Learning</fullName>
            </value>
            <value>
                <fullName>Organization Learning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/Learning_Domain__c.object-meta.xml
<CustomObject>
    <label>Learning Domain</label>
    <nameField>
        <displayFormat>LD-{00000000}</displayFormat>
        <label>Learning Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning Domains</relationshipLabel>
    <relationshipName>Learning_Domains</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ConsultingHub/force-app/main/default/classes/OnboardingHelper.cls
public class OnboardingHelper {
    @InvocableMethod(label='Get Learnings' description='Gets learning records from string argument')
    public static List<List<Learning__c>> getLearnings(List<String> selections) {
        String query = 'SELECT Id, Name, Expected_Hours_to_Complete__c , Must_Complete__c  FROM Learning__c ';
        //query += 'WHERE Is_Master__c = true AND (Type__c = \'Role Learning\' OR Type__c = \'Organization Learning\' '; VH-3-9-21
        query += 'WHERE (Type__c = \'Role Learning\' OR Type__c = \'Organization Learning\' ';
        if(selections.size() > 0 ){
            query += ' OR Learning_Domain__c INCLUDES (' ;
            for(Integer i = 0; i < selections.size(); i++) {
                query += '\'' + selections[i] + '\',';
            }
            query = query.removeEnd(',');
            query += ')';
            System.debug('query='+query);        
        }
        query += ')';
        List<Learning__c> learnings  = Database.query(query);
        List<List<Learning__c>> returnedLearnings = new List<List<Learning__c>>{learnings};
        System.debug(returnedLearnings);
        return returnedLearnings;
    }
    
    
    
}