ConsultingHub/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Expected_Hours_to_Complete__c.field-meta.xml
<CustomField>
    <fullName>Expected_Hours_to_Complete__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Learning_Domain__c.field-meta.xml
<CustomField>
    <fullName>Learning_Domain__c</fullName>
    <label>Learning Domain</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JIA</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority determines in what order the IAs are encouraged to take the trainings.</description>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/Learning_Domain__c.object-meta.xml
<CustomObject>
    <label>Learning Domain</label>
    <nameField>
        <displayFormat>LD-{00000000}</displayFormat>
        <label>Learning Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning Domains</relationshipLabel>
    <relationshipName>Learning_Domains</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/fields/Onboarding_Domain__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Domain__c</fullName>
    <label>Onboarding Domain</label>
    <referenceTo>Onboarding_Domain__c</referenceTo>
    <relationshipLabel>Learning Domains</relationshipLabel>
    <relationshipName>Learning_Domains</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Junction object that connects Onboarding record &amp; Learning records</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Hours_Required__c.field-meta.xml
<CustomField>
    <fullName>Hours_Required__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Must_Complete_By__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete_By__c</fullName>
    <label>Must Complete By</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Onboarding_Domain__c/Onboarding_Domain__c.object-meta.xml
<CustomObject>
    <label>Onboarding Domain</label>
    <nameField>
        <label>Onboarding Domains Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/classes/OnboardingFlowHelperTest.cls
@isTest 
public class OnboardingFlowHelperTest {
    static testMethod void testGetLearningFromSelectedDomains() {
       	Onboarding_Domain__c ob = new Onboarding_Domain__c();
       	ob.Name = 'testDomain';
        insert ob;
        
        Learning__c learningRecord = new Learning__c();
        learningRecord.Name = 'testLearning';
        learningRecord.Expected_Hours_to_Complete__c = 1;
        learningRecord.Priority__c = 1;
        insert learningRecord;
        
        Learning_Domain__c ld = new Learning_Domain__c();
        ld.Learning__c = learningRecord.Id;
        ld.Onboarding_Domain__c = ob.Id;
        insert ld;
        
        List<List<Onboarding_Domain__c>> selections = new List<List<Onboarding_Domain__c>> {new List<Onboarding_Domain__c>{ob}};
        
        
        Test.startTest();
        
        OnboardingFlowHelper.getLearningFromSelectedDomains(selections);
        
        Test.stopTest();
      
    }
    
    static testMethod void getAssignedModulesTest()
    {
        Onboarding__c onboard = TestDataFactory.createOnboardingRecord();
        
        Learning__c learningRecord = new Learning__c();
        learningRecord.Name = 'testLearning';
        learningRecord.Expected_Hours_to_Complete__c = 1;
        learningRecord.Priority__c = 1;
        insert learningRecord;
        
        List<Module__c> modulesToInsert = new List<Module__c>();
        
        Module__c test1 = new Module__c();
        test1.Hours_Required__c = 1;
        test1.Learning__c = learningRecord.Id;
        test1.Name = 'Test 1';
        test1.Must_Complete_By__c = Date.today();
        test1.Onboarding__c = onboard.Id;
        test1.Sort_Order__c = 1;
		modulesToInsert.add(test1);
        
        Module__c test2 = new Module__c();
        test2.Hours_Required__c = 1;
        test2.Learning__c = learningRecord.Id;
        test2.Name = 'Test 2';
        test2.Must_Complete_By__c = Date.today();
        test2.Onboarding__c = onboard.Id;
        test2.Sort_Order__c = 2;
        modulesToInsert.add(test2);
        
        insert modulesToInsert;
        
        List<Module__c> modulesReturned = OnboardingFlowHelper.getAssignedModules(onboard.Id);
        
        System.assertEquals(2, modulesReturned.size());
        System.assertEquals('Test 1', modulesReturned[0].Name);
        System.assertEquals('Test 2', modulesReturned[1].Name);
        System.assertEquals(1 , modulesReturned[0].Sort_Order__c);
        System.assertEquals(2 , modulesReturned[1].Sort_Order__c);
    }
    
    static testMethod void updateModulesTest()
    {
        Onboarding__c onboard = TestDataFactory.createOnboardingRecord();
        
        Learning__c learningRecord = new Learning__c();
        learningRecord.Name = 'testLearning';
        learningRecord.Expected_Hours_to_Complete__c = 1;
        learningRecord.Priority__c = 1;
        insert learningRecord;
        
        List<Module__c> modulesToInsert = new List<Module__c>();
        
        Module__c test1 = new Module__c();
        test1.Hours_Required__c = 1;
        test1.Learning__c = learningRecord.Id;
        test1.Name = 'Test 1';
        test1.Must_Complete_By__c = Date.today();
        test1.Onboarding__c = onboard.Id;
        test1.Sort_Order__c = 1;
		modulesToInsert.add(test1);
        
        Module__c test2 = new Module__c();
        test2.Hours_Required__c = 1;
        test2.Learning__c = learningRecord.Id;
        test2.Name = 'Test 2';
        test2.Must_Complete_By__c = Date.today();
        test2.Onboarding__c = onboard.Id;
        test2.Sort_Order__c = 2;
        modulesToInsert.add(test2);
        
        insert modulesToInsert;
        
        List<Module__c> modulesToUpdate = new List<Module__c>();
        Module__c test1Get = [Select Id, Name From Module__c Where Id =: test1.Id];
        test1Get.Name = 'Test 1 Update';
        modulesToUpdate.add(test1Get);
        
        Module__c test2Get = [Select Id, Name From Module__c Where Id =: test2.Id];
        test2Get.Name = 'Test 2 Update';
        modulesToUpdate.add(test2Get);
        
        OnboardingFlowHelper.updateModules(modulesToUpdate);
        
        Module__c test1Updated = [Select Id, Name From Module__c Where Id =: test1.Id];
		System.assertEquals('Test 1 Update', test1Updated.Name);
        
        Module__c test2Updated = [Select Id, Name From Module__c Where Id =: test2.Id];
        System.assertEquals('Test 2 Update', test2Updated.Name);
        
    }
}