ConsultingHub/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Expected_Hours_to_Complete__c.field-meta.xml
<CustomField>
    <fullName>Expected_Hours_to_Complete__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Learning_Domain__c.field-meta.xml
<CustomField>
    <fullName>Learning_Domain__c</fullName>
    <label>Learning Domain</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JIA</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Must_Complete__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Must Complete</label>
    <type>Checkbox</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/Learning_Domain__c.object-meta.xml
<CustomObject>
    <label>Learning Domain</label>
    <nameField>
        <displayFormat>LD-{00000000}</displayFormat>
        <label>Learning Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning Domains</relationshipLabel>
    <relationshipName>Learning_Domains</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning_Domain__c/fields/Onboarding_Domain__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Domain__c</fullName>
    <label>Onboarding Domain</label>
    <referenceTo>Onboarding_Domain__c</referenceTo>
    <relationshipLabel>Learning Domains</relationshipLabel>
    <relationshipName>Learning_Domains</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Junction object that connects Onboarding record &amp; Learning records</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Hours_Required__c.field-meta.xml
<CustomField>
    <fullName>Hours_Required__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Must_Complete_By__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete_By__c</fullName>
    <label>Must Complete By</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Onboarding_Domain__c/Onboarding_Domain__c.object-meta.xml
<CustomObject>
    <label>Onboarding Domain</label>
    <nameField>
        <label>Onboarding Domains Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/classes/OnboardingFlowHelper.cls
public class OnboardingFlowHelper {
	
    @InvocableMethod(label='Query Learning Records' description='Gets learning records based on Learning Domains selected')
    public static List<List<Learning__c>> getLearningFromSelectedDomains(List<List<Onboarding_Domain__c>> selections) {
        system.debug('selections='+selections);
        List<Id> selectedOnboardingDomains = new List<Id>();
        for( Onboarding_Domain__c dom :selections[0] ) {
            if(dom != null) {
                selectedOnboardingDomains.add(dom.Id);
            }
            
        }
        System.debug('selectedOnboardingDomains='+selectedOnboardingDomains);
        
        Set<Id> associatedLearningIds = new Set<Id>();
        
        for( Learning_Domain__c ld : [	select 	Id, Learning__c, Onboarding_Domain__c 
                                      	from 	Learning_Domain__c 
                                      	where 	Onboarding_Domain__c IN :selectedOnboardingDomains] )
        {
            associatedLearningIds.add(ld.Learning__c);
        }
        
        List<Learning__c> learnings = [	select	Id, Name, Expected_Hours_to_Complete__c , Must_Complete__c  
                                       	from	Learning__c
                                      	where	Id IN :associatedLearningIds];
	
        List<List<Learning__c>> returnedLearnings = new List<List<Learning__c>>{learnings};
        System.debug(returnedLearnings);
        return returnedLearnings;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Module__c> getAssignedModules(String OnboardingId)
    {
        List<Module__c> modulesToReturn = new List<Module__c>();
        try
        {
            modulesToReturn = [Select Id, Name, Sort_Order__c, Must_Complete_By__c, Hours_Required__c 
                               From Module__c 
                               Where Onboarding__c =: OnboardingId
                               ORDER BY Sort_Order__c ASC];
        }
        catch(Exception ex)
        {
            System.debug('Exception: ' + ex);
        }
        
        return modulesToReturn;
    }
    
    @AuraEnabled
    public static void updateModules(List<Module__c> modules)
    {
        try
        {
            update modules;
        }
        catch(Exception ex)
        {
            System.debug('Exception: ' + ex);
        }
        
    }
}