ConsultingHub/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Expected_Hours_to_Complete__c.field-meta.xml
<CustomField>
    <fullName>Expected_Hours_to_Complete__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Learning__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority determines in what order the IAs are encouraged to take the trainings.</description>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Junction object that connects Onboarding record &amp; Learning records</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Hours_Required__c.field-meta.xml
<CustomField>
    <fullName>Hours_Required__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Must_Complete_By__c.field-meta.xml
<CustomField>
    <fullName>Must_Complete_By__c</fullName>
    <label>Must Complete By</label>
    <type>Date</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Module__c/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/classes/GetRelatedModulesTest.cls
/**
 * @description       : Tests GetRelatedModules
 * @author            : Charles Gallagher
 * @last modified on  : 05-26-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-26-2021   Charles Gallagher  Initial Version
**/
@isTest
public class GetRelatedModulesTest 
{
	static testMethod void getModulesTest()
    {
        Onboarding__c onboard = TestDataFactory.createOnboardingRecord();
        
        Learning__c learningRecord = new Learning__c();
        learningRecord.Name = 'testLearning';
        learningRecord.Expected_Hours_to_Complete__c = 1;
        learningRecord.Priority__c = 1;
        insert learningRecord;
        
        List<Module__c> modulesToInsert = new List<Module__c>();
        
        Module__c test1 = new Module__c();
        test1.Hours_Required__c = 1;
        test1.Learning__c = learningRecord.Id;
        test1.Name = 'Test 1';
        test1.Must_Complete_By__c = Date.today();
        test1.Onboarding__c = onboard.Id;
        test1.Sort_Order__c = 1;
		modulesToInsert.add(test1);
        
        Module__c test2 = new Module__c();
        test2.Hours_Required__c = 1;
        test2.Learning__c = learningRecord.Id;
        test2.Name = 'Test 2';
        test2.Must_Complete_By__c = Date.today();
        test2.Onboarding__c = onboard.Id;
        test2.Sort_Order__c = 2;
        modulesToInsert.add(test2);
        
        insert modulesToInsert;
        
        List<Module__c> modulesReturned = GetRelatedModules.getModules(onboard.Id);
        
        System.assertEquals(2, modulesReturned.size());
        System.assertEquals('Test 1', modulesReturned[0].Name);
        System.assertEquals('Test 2', modulesReturned[1].Name);
    }
}