ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>This object contains the engagement activities tied to this specific engagement along with their statuses. At the time of engagement creation the activities get cloned here based on the engagement type.</description>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA - {000000}</displayFormat>
        <label>Engagement Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Stage_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Skip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/ia_Engagement__c.object-meta.xml
<CustomObject>
    <description>Document details of on going and completed engagements</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select based on type and domain of engagement (e.g. Sales Cloud, Service Cloud, CPQ, FSL, etc.)</inlineHelpText>
    <label>Engagement Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ia_Engagement_Type__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ia_Engagement_Type__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Implementation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Implementation_Type</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Managed By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Project_Management</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/ia_Engagement_Type__c.object-meta.xml
<CustomObject>
    <description>This object will be used to distinguish different types of engagement</description>
    <label>Engagement Type</label>
    <nameField>
        <label>Engagement Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/RACI__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Activity and Stakeholder objects</description>
    <label>RACI</label>
    <nameField>
        <displayFormat>RACI-{00000}</displayFormat>
        <label>RACI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RACI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>RACI</relationshipLabel>
    <relationshipName>RACI</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/RACI__c.field-meta.xml
<CustomField>
    <fullName>RACI__c</fullName>
    <label>RACI</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R - Responsible</fullName>
            </value>
            <value>
                <fullName>A - Accountable</fullName>
            </value>
            <value>
                <fullName>C - Consulted</fullName>
            </value>
            <value>
                <fullName>I  - Informed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipLabel>RACI</relationshipLabel>
    <relationshipName>RACI</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <description>This reference object contains all the Stakeholders that the activities will be tied to.</description>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/classes/GetRelatedRACITest.cls
/**
 * @description       : Tests for GetRelatedRACI
 * @author            : Charles Gallagher
 * @last modified on  : 05-05-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-05-2021   Charles Gallagher  Initial Version
**/

@isTest
public class GetRelatedRACITest 
{
    @isTest(SeeAllData=true)
    static void testGettingRACI()
    {
        //Dependant on there being an IA Method 2.0 Type because this type has further automation attached to it on the 
        //Engagement Trigger
        ia_Engagement_Type__c engagementType = [Select Id From ia_Engagement_Type__c Where Name = 'IA Method 2.0' Limit 1];
        
        //Create test ia_Engagement__c 
        ia_Engagement__c testEngagement = new ia_Engagement__c();
        testEngagement.Name = 'Test Engagement';
        testEngagement.Implementation_Type__c = 'New';
        testEngagement.Project_Type__c = 'Customer';
        testEngagement.Status__c = 'Scheduled';
        testEngagement.Engagement_Type__c = engagementType.Id;
        
        insert testEngagement;
        
        //Get related Engagement_Activity__c and Stage activity
        Engagement_Activity__c ea = [Select Id, Activity__c From Engagement_Activity__c Where Engagement__c =: testEngagement.Id Limit 1];
        
        //Create Stake Holder
        Stakeholder__c stakeHolder = new Stakeholder__c();
        stakeHolder.Name = 'Test';
        insert stakeHolder;
        
        //Create RACI
        RACI__c raci = new RACI__c();
        raci.Activity__c = ea.Activity__c;
        raci.Stakeholder__c = stakeHolder.Id;
        raci.RACI__c = 'R - Responsible';
        insert raci;
        
        Test.startTest();
        
        List<RACI__c> returnedRACI = GetRelatedRACI.getRACI(ea.Id);
                
        Test.stopTest();
        
        RACI__c chosenRACI = [Select Id, Name, Stakeholder__c, RACI__c FROM RACI__c WHERE Id =: raci.Id];
        RACI__c raciToCheckAgainst;
        
        for(RACI__c temp : returnedRACI)
        {
            if(temp.Id == raci.Id)
            {
                raciToCheckAgainst = temp;
            }
        }

        System.assertEquals(chosenRACI.Name, raciToCheckAgainst.Name);
        System.assertEquals(chosenRACI.Stakeholder__c, raciToCheckAgainst.Stakeholder__c);
        System.assertEquals(chosenRACI.RACI__c, raciToCheckAgainst.RACI__c);
    }

}