ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>This object contains the engagement activities tied to this specific engagement along with their statuses. At the time of engagement creation the activities get cloned here based on the engagement type.</description>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA - {000000}</displayFormat>
        <label>Engagement Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Output__c.field-meta.xml
<CustomField>
    <fullName>Output__c</fullName>
    <label>Output</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Resources_and_Templates__c.field-meta.xml
<CustomField>
    <fullName>Resources_and_Templates__c</fullName>
    <label>Resources and Templates</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>Activity__r.Stage__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Skip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Deliverable__c/ia_Deliverable__c.object-meta.xml
<CustomObject>
    <description>To be attached to each Phase</description>
    <label>Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Deliverable__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Implementation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Implementation_Type</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/ia_Engagement__c.object-meta.xml
<CustomObject>
    <description>Document details of on going and completed engagements</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select based on type and domain of engagement (e.g. Sales Cloud, Service Cloud, CPQ, FSL, etc.)</inlineHelpText>
    <label>Engagement Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ia_Engagement_Type__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ia_Engagement_Type__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Implementation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Implementation_Type</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Managed By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Project_Management</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/ia_Engagement_Type__c.object-meta.xml
<CustomObject>
    <description>This object will be used to distinguish different types of engagement</description>
    <label>Engagement Type</label>
    <nameField>
        <label>Engagement Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/Stage_Activity__c.object-meta.xml
<CustomObject>
    <description>This is a reference object of activities that are tied to specific Phase and Stage of an Engagement Type.</description>
    <label>Stage Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The activity detail</description>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/fields/Output__c.field-meta.xml
<CustomField>
    <fullName>Output__c</fullName>
    <label>Output</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/fields/Resources_and_Templates__c.field-meta.xml
<CustomField>
    <fullName>Resources_and_Templates__c</fullName>
    <label>Resources and Templates</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <referenceTo>ia_Deliverable__c</referenceTo>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/classes/EngagementTrigger_Test.cls
/**
02/23/2021 - VH - Test class for EngageActivityTrigger
                  Code coverage is 100%

**/
@isTest
public class EngagementTrigger_Test {
    
        //--------------------------------------------
        //----------- initial test data setup --------
        //--------------------------------------------

    @isTest
    public static void testInsertUpdate() {
        //build IA Method 2.0 Engagement Type
        ia_Engagement_Type__c engType = new ia_Engagement_Type__c();
        
        engType.Name = 'IA Method 2.0';
        engType.Status__c = 'Active';
        
        insert engType;
        
        //build Engagement
        ia_Engagement__c testEng = new ia_Engagement__c();
        testEng.Name = 'Testing 123';
        testEng.Implementation_Type__c = 'New';
        testEng.Project_Type__c = 'Customer';
        testEng.Status__c = 'Scheduled';
        testEng.Engagement_Type__c = engType.Id;

		//build ia_Deliverable__c
        ia_Deliverable__c stage = new ia_Deliverable__c();
        stage.name = 'Kickoff';
        
        insert stage;
        //build stage activities
        List<Stage_Activity__c> stageActivities_list = new List<Stage_Activity__c>();
        Stage_Activity__c stageAct1 = new Stage_Activity__c();
        stageAct1.Output__c='Sample output 1';
        stageAct1.Resources_and_Templates__c='Resources_and_Templates__c 1';
        stageAct1.Description__c ='Test description 1';
        stageAct1.Stage__c = stage.Id;
        
        insert stageAct1; //insert first stage activity
        
        Stage_Activity__c stageAct2 = new Stage_Activity__c();
        stageAct2 = new Stage_Activity__c();
        stageAct2.Output__c='Sample output 2';
        stageAct2.Resources_and_Templates__c='Resources_and_Templates__c 2';
        stageAct2.Description__c ='Test description 2';
        stageAct2.Stage__c = stage.Id;
        
        insert stageAct2; //insert second stage activity
        
        Test.startTest();
        Database.insert(testEng);
        List<Engagement_Activity__c> engActList = [select Id from Engagement_Activity__c
                                                  where Engagement__c=: testEng.id];
        System.assertEquals(2, engActList.size());
        Test.stopTest();
        
    }

    @isTest
    public static void testUpdate() {
        //build IA Method 2.0 Engagement Type
        ia_Engagement_Type__c engType = new ia_Engagement_Type__c();
        
        engType.Name = 'IA Method 2.0';
        engType.Status__c = 'Active';
        
        insert engType;
        
        //build Engagement
        ia_Engagement__c testEng = new ia_Engagement__c();
        testEng.Name = 'Testing 123';
        testEng.Implementation_Type__c = 'New';
        testEng.Project_Type__c = 'Customer';
        testEng.Status__c = 'Scheduled';
        //testEng.Engagement_Type__c = engType.Id;

		//build ia_Deliverable__c
        ia_Deliverable__c stage = new ia_Deliverable__c();
        stage.name = 'Kickoff';
        
        insert stage;
        //build stage activities
        List<Stage_Activity__c> stageActivities_list = new List<Stage_Activity__c>();
        Stage_Activity__c stageAct1 = new Stage_Activity__c();
        stageAct1.Output__c='Sample output 1';
        stageAct1.Resources_and_Templates__c='Resources_and_Templates__c 1';
        stageAct1.Description__c ='Test description 1';
        stageAct1.Stage__c = stage.Id;
        
        insert stageAct1; //insert first stage activity
        
        Stage_Activity__c stageAct2 = new Stage_Activity__c();
        stageAct2 = new Stage_Activity__c();
        stageAct2.Output__c='Sample output 2';
        stageAct2.Resources_and_Templates__c='Resources_and_Templates__c 2';
        stageAct2.Description__c ='Test description 2';
        stageAct2.Stage__c = stage.Id;
        
        insert stageAct2; //insert second stage activity
        
        Test.startTest();
        Database.insert(testEng);
        List<Engagement_Activity__c> engActList = [select Id from Engagement_Activity__c
                                                  where Engagement__c=: testEng.id];
        System.assertEquals(0, engActList.size());
        
        testEng.Engagement_Type__c = engType.Id;
        Database.update(testEng);
        List<Engagement_Activity__c> engActList2 = [select Id from Engagement_Activity__c
                                                  where Engagement__c=: testEng.id];
        System.assertEquals(2, engActList2.size());
        Test.stopTest();
        
    }

}