ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>This object contains the engagement activities tied to this specific engagement along with their statuses. At the time of engagement creation the activities get cloned here based on the engagement type.</description>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA - {000000}</displayFormat>
        <label>Engagement Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Stage_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement</label>
    <referenceTo>ia_Engagement__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Engagement_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Skip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/ia_Asset__c.object-meta.xml
<CustomObject>
    <description>Asset maintained by the Implementation Architect team</description>
    <label>IA Asset</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IA Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Demonstration</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>KB Article</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>User Guide</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>AppExchange Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Choose the language for the Asset</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field defaults to New on creation.  When a new IA Asset is created by a non IA Engage Admin user, a process builder notifies the admin user group accordingly so that they can review the asset to determine if it should be added as an engagement type asset.  This field supports that process builder criteria and can be used to track process of the review.</description>
    <inlineHelpText>Tracks the review of new IA Assets to monitor duplicates and create Engagement Type Assets as needed.

-Defaults to New
-Process marks Submitted
-Reviewer can update to In Progress or Needs Revision
-Complete when done</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Needs Revision</fullName>
            </value>
            <value>
                <fullName>Submitted for Review</fullName>
            </value>
            <value>
                <fullName>Review in Progress</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/ia_Engagement__c.object-meta.xml
<CustomObject>
    <description>Document details of on going and completed engagements</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select based on type and domain of engagement (e.g. Sales Cloud, Service Cloud, CPQ, FSL, etc.)</inlineHelpText>
    <label>Engagement Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ia_Engagement_Type__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ia_Engagement_Type__c</referenceTo>
    <relationshipLabel>Engagements</relationshipLabel>
    <relationshipName>Engagement</relationshipName>
    <type>Lookup</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Implementation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Implementation_Type</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Managed By</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ia_Project_Management</valueSetName>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/ia_Engagement_Type__c.object-meta.xml
<CustomObject>
    <description>This object will be used to distinguish different types of engagement</description>
    <label>Engagement Type</label>
    <nameField>
        <label>Engagement Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Engagement_Type__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/Stage_Activity__c.object-meta.xml
<CustomObject>
    <description>This is a reference object of activities that are tied to specific Phase and Stage of an Engagement Type.</description>
    <label>Stage Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/Stage_Activity_Asset__c.object-meta.xml
<CustomObject>
    <label>Stage Activity Asset</label>
    <nameField>
        <displayFormat>SAA-{0000}</displayFormat>
        <label>Stage Activity Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activity Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/fields/IA_Asset__c.field-meta.xml
<CustomField>
    <fullName>IA_Asset__c</fullName>
    <label>IA Asset</label>
    <referenceTo>ia_Asset__c</referenceTo>
    <relationshipLabel>Stage Activity Assets</relationshipLabel>
    <relationshipName>Stage_Activity_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/fields/Stage_Activity__c.field-meta.xml
<CustomField>
    <fullName>Stage_Activity__c</fullName>
    <label>Stage Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Stage Activity Assets</relationshipLabel>
    <relationshipName>Stage_Activity_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/classes/GetRelatedIAAssetsTests.cls
/**
 * @description       : Tests for GetRelatedIAAssets
 * @author            : Charles Gallagher
 * @last modified on  : 05-04-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-04-2021   Charles Gallagher  Initial Version
**/

@isTest
public class GetRelatedIAAssetsTests {

    @isTest(SeeAllData=true)
    static void testGettingAssets()
    {
        //Dependant on there being an IA Method 2.0 Type because this type has further automation attached to it on the 
        //Engagement Trigger
        ia_Engagement_Type__c engagementType = [Select Id From ia_Engagement_Type__c Where Name = 'IA Method 2.0' Limit 1];
        
        //Create test ia_Engagement__c 
        ia_Engagement__c testEngagement = new ia_Engagement__c();
        testEngagement.Name = 'Test Engagement';
        testEngagement.Implementation_Type__c = 'New';
        testEngagement.Project_Type__c = 'Customer';
        testEngagement.Status__c = 'Scheduled';
        testEngagement.Engagement_Type__c = engagementType.Id;
        
        insert testEngagement;
        
        //Get related Engagement_Activity__c and Stage activity
        Engagement_Activity__c ea = [Select Id, Activity__c From Engagement_Activity__c Where Engagement__c =: testEngagement.Id Limit 1];

        //Create an IA Asset to test with 
        ia_Asset__c asset = new ia_Asset__c();
        asset.Name__c = 'Test';
        asset.Asset_Type__c = 'Site';
        asset.Language__c = 'English';
        asset.Location__c = 'http://pages.test.salesforce.com/test/test';
        asset.Status__c = 'New';
        
        insert asset;
        
        //Create Stage_Activity_Asset__c
        Stage_Activity_Asset__c stageAsset = new Stage_Activity_Asset__c();
		stageAsset.IA_Asset__c = asset.Id;
		stageAsset.Stage_Activity__c = ea.Activity__c;
        insert stageAsset;
        
        //Run getAssets
        Test.startTest();
        
        List<ia_Asset__c> returnedAssets = GetRelatedIAAssets.getAssets(ea.Id);
        
        Test.stopTest();
        
        ia_Asset__c iaToCheckAgainst;
        
        for(ia_Asset__c temp : returnedAssets)
        {
            if(temp.Id == asset.Id)
            {
                iaToCheckAgainst = temp;
            }
        }
        
        System.assertEquals(asset.Name__c, iaToCheckAgainst.Name__c);
        System.assertEquals(asset.Asset_Type__c, iaToCheckAgainst.Asset_Type__c);
        System.assertEquals(asset.Location__c, iaToCheckAgainst.Location__c);
    }
}