ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>This object contains the engagement activities tied to this specific engagement along with their statuses. At the time of engagement creation the activities get cloned here based on the engagement type.</description>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA - {000000}</displayFormat>
        <label>Engagement Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Stage_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/ia_Asset__c.object-meta.xml
<CustomObject>
    <description>Asset maintained by the Implementation Architect team</description>
    <label>IA Asset</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IA Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Demonstration</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>KB Article</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>User Guide</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Worksheet</fullName>
            </value>
            <value>
                <fullName>AppExchange Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/ia_Asset__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity__c/Stage_Activity__c.object-meta.xml
<CustomObject>
    <description>This is a reference object of activities that are tied to specific Phase and Stage of an Engagement Type.</description>
    <label>Stage Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/Stage_Activity_Asset__c.object-meta.xml
<CustomObject>
    <label>Stage Activity Asset</label>
    <nameField>
        <displayFormat>SAA-{0000}</displayFormat>
        <label>Stage Activity Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Activity Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/fields/IA_Asset__c.field-meta.xml
<CustomField>
    <fullName>IA_Asset__c</fullName>
    <label>IA Asset</label>
    <referenceTo>ia_Asset__c</referenceTo>
    <relationshipLabel>Stage Activity Assets</relationshipLabel>
    <relationshipName>Stage_Activity_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stage_Activity_Asset__c/fields/Stage_Activity__c.field-meta.xml
<CustomField>
    <fullName>Stage_Activity__c</fullName>
    <label>Stage Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Stage Activity Assets</relationshipLabel>
    <relationshipName>Stage_Activity_Assets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/classes/GetRelatedIAAssets.cls
/**
 * @description       : Gets related IA Assets associated to a specific Engagement Activity
 * @author            : Charles Gallagher
 * @last modified on  : 05-03-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-03-2021   Charles Gallagher  Initial Version
**/
public class GetRelatedIAAssets 
{
    @AuraEnabled(cacheable=true)
    public static List<ia_Asset__c> getAssets(Id engagmentActivityId)
    {
        List<ia_Asset__c> listToReturn = new List<ia_Asset__c>();
        try
        {
            //Get the Activity__c related to the engagmentActivity
            Engagement_Activity__c engagmentActivity = [Select Id, Activity__c FROM Engagement_Activity__c WHERE Id =: engagmentActivityId];

            //From the Stage Activty get all the related Stage Activity Assets and IA Asset Ids
            List<Stage_Activity_Asset__c> stageActivityAssets = [Select Id, IA_Asset__r.Id  FROM Stage_Activity_Asset__c Where Stage_Activity__c =: engagmentActivity.Activity__c];
            
            //Make a set of all the unique IA Asset Ids
            Set<Id> iaAssetIds = new Set<Id>();
                        
            for(Stage_Activity_Asset__c asset : stageActivityAssets)
            {
                iaAssetIds.add(asset.IA_Asset__r.Id);
            }

            //Gets list of related IA Assets 
            listToReturn = [Select Id, Name, Name__c, Asset_Type__c, Location__c FROM ia_Asset__c WHERE Id IN : iaAssetIds];
            
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
        return listToReturn;
        
    }
}