ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/Engagement_Activity__c.object-meta.xml
<CustomObject>
    <description>This object contains the engagement activities tied to this specific engagement along with their statuses. At the time of engagement creation the activities get cloned here based on the engagement type.</description>
    <label>Engagement Activity</label>
    <nameField>
        <displayFormat>EA - {000000}</displayFormat>
        <label>Engagement Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/Engagement_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>Engagement Activities</relationshipLabel>
    <relationshipName>Stage_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/RACI__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between Activity and Stakeholder objects</description>
    <label>RACI</label>
    <nameField>
        <displayFormat>RACI-{00000}</displayFormat>
        <label>RACI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RACI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Stage_Activity__c</referenceTo>
    <relationshipLabel>RACI</relationshipLabel>
    <relationshipName>RACI</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/RACI__c.field-meta.xml
<CustomField>
    <fullName>RACI__c</fullName>
    <label>RACI</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R - Responsible</fullName>
            </value>
            <value>
                <fullName>A - Accountable</fullName>
            </value>
            <value>
                <fullName>C - Consulted</fullName>
            </value>
            <value>
                <fullName>I  - Informed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConsultingHub/force-app/main/default/objects/RACI__c/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <label>Stakeholder</label>
    <referenceTo>Stakeholder__c</referenceTo>
    <relationshipLabel>RACI</relationshipLabel>
    <relationshipName>RACI</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ConsultingHub/force-app/main/default/objects/Stakeholder__c/Stakeholder__c.object-meta.xml
<CustomObject>
    <description>This reference object contains all the Stakeholders that the activities will be tied to.</description>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConsultingHub/force-app/main/default/classes/GetRelatedRACI.cls
/**
 * @description       : Gets related RACI records associated to a specific Engagement Activity
 * @author            : Charles Gallagher
 * @last modified on  : 05-05-2021
 * @last modified by  : Charles Gallagher
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   05-05-2021   Charles Gallagher  Initial Version
**/
public class GetRelatedRACI 
{
    @AuraEnabled(cacheable=true)
    public static List<RACI__c > getRACI(Id engagmentActivityId)
    {
        List<RACI__c> listToReturn = new List<RACI__c>();
        try
        {
            //Get the Activity__c related to the engagmentActivity
            Engagement_Activity__c engagmentActivity = [Select Id, Activity__c FROM Engagement_Activity__c WHERE Id =: engagmentActivityId];

            //From the Stage Activty get all the related Stage Activity Assets and IA Asset Ids
            listToReturn = [Select Id, RACI__c, Name, Stakeholder__r.Name FROM RACI__c  Where Activity__c =: engagmentActivity.Activity__c];
            
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage());    
        }
        return listToReturn;
    }

}